### ISSUE TITLE
Story: Support voting with dollars - Take 2

### ISSUE THREAD

**Issue by jeksmith** [danielsomerfield/yer-song#12]
As a YerSong band of musicians, I want to allow audience members to donate dollars to request songs in order to incite other audience members to bid up their requests so that we can increase donations while everyone has fun.

A.C.s
* Votes will have $dollars as units.
* There will be no "free" votes.
* A person can vote more than once for the same song, i.e., send more money in another transaction.
* The previous voting behavior is preserved for wedding-like events.
* There is a new Transaction Monitor interface as described below.
* Changes are made to the Audience Member and Big Board (screen) interfaces as described below.
* Venmo payee and default request value is configurable

Typical Audience Member (AM) workflow:

1 - AM scans either a printed or projected (on the screen) QRCode 
2 - Browser application loads and user puts in her or his name (Curly in our scenario)
3 - Main menu appears, user can look at the current playlist or browse for a song
4 - User selects a song. If the song isn’t already requested, something like this appears:

> Song: Come and Get It
> Artist: Badfinger
> 
> Request:  [ $5 ]  [Venmo]    <— This is a textbox and a button.

5 - User “touches” `Venmo` button and is sent to Venmo app. Payee, Amount, and Note with the song name in it is pre-filled in. Here is the url used: `https://venmo.com/?txn=pay&audience=friends&recipients=PAYEE&amount=5.00&note=3%20Stooges%20Theme`, as generated by: [Venmo Payment Links](https://venmo.com/paymentlinks/), where PAYEE is the target Venmo user name.
6 - User hits the Pay button in Venmo app and then confirms it as the Venmo UI requires

The user is now in the Venmo app and with the payment complete, nothing more has to be done by the user. At this point, the song has a pending 5-vote status in YerSong. Since we cannot know for sure if the transaction succeeded, there is a manual step necessary. (See next section.)

— — Venmo Monitor workflow — — 

1 - The Venmo monitor sees a list of Venmo requests made in the YerSong app when AMs touch the Venmo buttons. It will look something like:

> Action - - - Amount - - Requester - - Title
> [Confirm] - [ $5 ] - - - - - Moe - - - - 3 Stooges Theme
> [Confirm] - [ $7 ] - - - - - Larry - - - - Undercover Angel
> [Confirm] - [ $5 ] - - - - - Curly - - - - Come and Get It
> Confirmed - $10 - - - - - Moe - - - - - Material Girl
> Confirmed - $3 - - - - - - Curly - - - - Thriller

Note: The top three have yet to be confirmed. For those, there is a `Confirm` button and a textbox with a changeable amount so that the monitor can override the initial $$ value for any reason.

2 - The monitor sees the first two transactions come through on the Venmo UI and then presses `Confirm` for them on the YerSong UI.
3 - Upon confirmation, the votes are added to the YerSong system and the songs are either added to the playlist (if they weren’t there previously) or the additional votes are added to the existing tally.
4 - The monitor now waits for the remaining transaction by Curly to come through on the Venmo UI. (It is the only unconfirmed transaction at this point.)

— — Big Board (Screen) — — 

The Big Board shows locked songs at the top (usually the currently played song), followed by the playlist sorted by votes/dollars (only confirmed requests appear). Here’s what it may look like for our scenario after the monitor has confirmed all but Curly’s most recent request:

> Title - - - - - - - - - - Requester - - - - - - Amount
> Eleanor Rigby - - - - John - - - - - - - - - [padlock]    (no amount shown for locked songs)
> Material Girl - - - - - Moe - - - - - - - - - - $10
> Undercover Angel - Larry - - - - - - - - - - $7
> 3 Stooges Theme - - Moe - - - - - - - - - - $5
> Thriller - - - - - - - - Curly - - - - - - - - - - $3

Note: if someone wants to bump up Thriller, then she or he can put in some $$ and it will be added to Curly’s $3. Even Curly himself can do this.

**Comment by danielsomerfield** [comment]
One risk is that the user submits a request but then the band runs out of time and they don't get to hear their song. Any thoughts on that? I could imagine having a way to lock the bidding process, but even that might not do it. Can the quartet refund amounts through Venmo?

**Comment by danielsomerfield** [comment]
Tasking it out:

# AM Workflow: Song Request
* Submit request
  * Record request in yersong as unconfirmed
  * Send user to Venmo with details filed out 
    * include transaction id in note to ease VM approval process
# VM Workflow: Approve Song
* Render current requests for admin
* Approve request
  * On approval, add dollar value to total
  * Remove logic preventing a user from voting for the same song twice 
# BB View
* Show dollars (rather than votes)

**Comment by danielsomerfield** [comment]
@jeksmith - what is the smallest increment? Can someone bid $1.23, or is it whole dollars?

**Comment by danielsomerfield** [comment]
@jeksmith -

These two ACs might not be in this release. 

- The previous voting behavior is preserved for wedding-like events.
- Venmo payee and default request value is configurable

**Comment by jeksmith** [comment]
> One risk is that the user submits a request but then the band runs out of time and they don't get to hear their song. Any thoughts on that? I could imagine having a way to lock the bidding process, but even that might not do it. Can the quartet refund amounts through Venmo?

@danielsomerfield Yep, this is a risk and has, in fact, happened. Previously the quartet announced about 20 minutes before the end that they probably wouldn't be able to play all the requests made via Venmo. Previously there was no real visibility into the queue, songs got lost, so really all is much better now. I think a better feature than a cut off would be to show an estimated play time in the playlist--we'd need to have song lengths also--clearly a future feature. At this point, it is on the quartet to communicate this and make it clear that Venmo transactions are donations and not made for exact services. I think we're good here.

**Comment by jeksmith** [comment]
> @jeksmith - what is the smallest increment? Can someone bid $1.23, or is it whole dollars?

Whole dollars! Need to make it as simple as poss!

**Comment by jeksmith** [comment]
> @jeksmith -
> 
> These two ACs might not be in this release.
> 
> * The previous voting behavior is preserved for wedding-like events.
> * Venmo payee and default request value is configurable

That's fine. If someone puts in for $50 and for some reason changes it to $5, we can just not approve the request.... speaking of, I was thinking about the monitor UI -- We need to think about a rogue kid user that just punches values and the Venmo button. The monitor UI should have the latest requests at the top. That way, older requests just hang out below the top. In the future we may allow the monitor to ignore/delete requests, but right now just ok to always sort the most recent on top.

**Comment by danielsomerfield** [comment]
@jeksmith - pushing the monitoring page shortly.

You will be able to see that at `https://yersong.danielsomerfield.com/dvAdmin`

 It doesn't do approval yet. That should come this afternoon.

**Comment by danielsomerfield** [comment]
A couple things to note: I've made the request id smaller and a random hash so it's easier to compare. The timestamp was a bad plan and redundant. I also have to deal with scrolling.
