### ISSUE TITLE
Grid is messed up on admin page

### ISSUE THREAD

**Issue by danielsomerfield** [danielsomerfield/yer-song#13]
<img width="1791" alt="image" src="https://github.com/danielsomerfield/yer-song/assets/6019932/a680ec8a-9613-4b01-8739-879e24c7af56">

It's supposed to look like that:

<img width="1735" alt="image" src="https://github.com/danielsomerfield/yer-song/assets/6019932/2155372b-cc58-4c03-b8d7-50eb7ce1a960">

Specifically, songs aren't supposed to be multiple to a row and the cells below should align to their headers.

**Comment by somesyd** [comment]
Fixed this one with issue #2 with PR #16. Replaced most of the grid css styling with an html table.
