### ISSUE TITLE
Bug: Description in Venmo payment message is Ugly/harder to read than it could be

### ISSUE THREAD

**Issue by jeksmith** [danielsomerfield/yer-song#21]
The description has pluses for spaces, which is expected for encoded URLs. My song is coming across as:

Song:+All+My+Loving+-+RequestId:+202412503415947249205+

This may be inevitable, but if we could get spaces to appear in Venmo, that would be great for visibility/readability of the monitor to match transactions with requests.

**Comment by danielsomerfield** [comment]
Had a local fix for this already that I didn't push. It's up there now. It's still not beautiful. You can only do so much, but it's more legible.
