### ISSUE TITLE
Story: Admin can ignore requests

### ISSUE THREAD

**Issue by danielsomerfield** [danielsomerfield/yer-song#23]
Placeholder: you can "approve" but you can't purge ones you don't want to approve. The list could pile up with junk. Need something here, details TBD.

**Comment by jeksmith** [comment]
I think as long as the newest ones are always on top we'll be ok. It probably would be good to be able to ignore/archive them, but we can probably live without.

**Comment by jeksmith** [comment]
This has been addressed with a new Reject button. Thank you!
