### ISSUE TITLE
Support voting with dollars

### ISSUE THREAD

**Issue by jeksmith** [danielsomerfield/yer-song#6]
As a band member, I'd like to get the audience in a bidding war to get a desired song heard so that I can make more moola.

A.C.s
* A user can add money to any song any amount of times.
* Once added, money cannot be removed from a song (different than regular voting).
* The primary sorting is by money, secondary by regular votes (if votes still exist).
* Way to configure where the money goes (which TO Venmo account).

Venmo is the preferred money exchanger.

Some things discussed:
- integrate with Venmo per "vote"
- integrate with Venmo in a batch and then vote from a pool of $s
- Existing votes become dollars--refilled via codes handed out at the show. Would need to change vote implementation to allow more than 1 vote per song AND have votes come from a pool of votes.

Example big screen:
`Billy Jean      PADLOCK  Pete`
`Start Me Up      $20  4  JoJo`
`Band on the Run  $11  1  Ken`
`Drive My Car     $10  2  Fred`
`Piano Man         $0  4  Goober`
`Let It Be         $0  1  MotherMary`

**Comment by danielsomerfield** [comment]
@jeksmith - I think this one's going to be tough. Here is the deal:
- the [developer API](https://venmo.com/docs/overview/) is dead. They are not issuing any new accounts for it. 
- the "feed" is dead. It got too many privacy complaints.
- In theory, this could be done with a [business profile](https://venmo.com/business/profiles/) but we can't tell for sure. Venmo doesn't work in Canada at all, we aren't even able to sign up for an account so we would have not ability to run and test or even confirm that it does what we need.

In short, even if we could get you to do the stuff we can't here, it'd be slow going without being able to do much ourselves. 

We _could_ do paypal, potentially, but their per-transaction [fees](https://www.paypal.com/ca/webapps/mpp/merchant-fees#ffees) are a lot higher: starting $0.30 plus a percentage. Seems pretty steep for small transactions. They offer a micropayment plan but you have to talk to them which suggests they expect high volume.

In summary: there are a bunch of challenges here, particularly on a short timeline. Any thoughts about whether we should just say "no for now"?

**Comment by jeksmith** [comment]
The business profile seems too steep a lift for the 2-week deadline. The below looks like it may be simple… but maybe not? Bonus is we get both Venmo and PayPal. I think.

https://developer.paypal.com/docs/checkout/pay-with-venmo/

I'll see if I can prove that out fairly quickly.

I do have another idea: Someone could monitor the Venmo feed and hand enter the money votes in. That would require a view that allows money to be entered in -- or we can leave it votes and each dollar buys 5 votes (or something like that). The vote view would support selecting a song, putting in a name and number of votes. Could do that to any song... just inserts.

**Comment by danielsomerfield** [comment]
I have read that the Venmo global feed is dead (too many privacy
complaints). Otherwise, I think this would be easy.

https://www.theverge.com/2021/7/20/22585467/venmo-removes-global-social-feed-private-payments

It looks like the "friends" feed is still there, so everyone would have to
friend the string quartet and presumably they'd have to approve it? Not
sure. Again, can't see it from Canada, so we have no way to tell.

**Comment by jeksmith** [comment]
There are two hacky ways to do this, but they are too risky in failure....
1) Use a virtual browser or otherwise jump through the hoops and monitor the user's me-feed
2) Use Zapier/IFTTT to parse emails sent to the user
Both of these have the problem of connecting the YerSong user to the Venmo transaction and song choice.

I'm going to send a message to the strings to see if they have a Venmo business profile set up and time in the next couple of days. Also going to put a couple of plan B's in there, but obviously need to run those by you before committing.

**Comment by jeksmith** [comment]
Closing this, as it is superceded by https://github.com/danielsomerfield/yer-song/issues/12
