### ISSUE TITLE
Story: Admin Login

### ISSUE THREAD

**Issue by danielsomerfield** [danielsomerfield/yer-song#7]
As a musician playing a concern with this system, I don't want just anyone to do certain things. I need those administration functions to be protected such that only those authorized to do them are able to.

**ACs**
* The following functions can only be executed by an administrator:
    * marking a song as played (`clearVotes`)
    * marking a song as "pinned" or "unpinned"
    * moving pinned songs up and down
* The admin must log in using an industry standard means of authentication (username / password), SSO, etc. Probably just be username / password for the time being.
* The admin credentials must not be stored in a public place such as github, but must be provided at installation time or be configurable via an AWS administrator.
* The system should not stored the password *at all* but rather store a encrypted, salted, hash of the password, such as that generated by bcrypt implementations.

**Out of scope**
* Multiple layers of authorization. Right now you are either an admin or not. At this point, there won't be a role for those who can, say, mark a song as played, and another one who can also move songs around. It's all or nothing.

**Comment by danielsomerfield** [comment]
Here are the tasks I see:
* if you go to the admin page and have not logged in, prompt for admin credentials
* on successful admin login, provide a jwt that contains an admin flag
* for search administrative functions: validate that the JWT contains the admin flag and reject the request if it doesn't

I believe that will be sufficient. Because JWTs are signed by the system, you can't modify yours to have the flag. Because it only provides that signed jwt if you log in successfully, the system should be secure. The only way to break this is to break the JWT encryption secret or steal the credentials.

**Comment by danielsomerfield** [comment]
@jeksmith - this isn't very well documented, but it is deployed.

Watch out for bug #13 and #4, but you should be able to give this a try. We'll work on fixing those two bugs next. 

To test:
- I will send you and invite to our AWS account
- You can use api/bin/add-admin.sh to add yourself as an administrator
- You can go to `https://yersong.danielsomerfield.com/admin` and log in.

If you try it before we get to #13, the grid will be wacky but it shouldn't prevent you from testing. If you try it before we get to #4, you'll need to delete your local storage for the app domain before logging in or it will just spin.

**Comment by jeksmith** [comment]
Yo. Am trying to add an admin, but having a problem running the command. Presumably I need to run `aws sso login` first, which itself requires `aws configure sso`. I didn't get the latter to take what I found as the URL in the SSO portion of the AWS account console. I think I just need to get jumpstarted here.

**Comment by danielsomerfield** [comment]
Ok. Let me know when you have some time and we can get you connected. I'm not sure I totally follow the problem so perhaps we can walk through it together.
